#!/usr/bin/env bash

# Author: @thePrimagen

# it would be nice to have a check that if I am in the searched directory but the current dir is not the one i searched for i cd to that one

if [[ $# -eq 1 ]]; then
  selected=$1
else
  selected=$(fd --type d --max-depth 1 --absolute-path '' ~/Library/Mobile\ Documents/iCloud~md~obsidian/Documents ~/.config ~/Documents/Github | fzf --style full --border --info=inline --margin=8,20 --padding=1 --preview='eza --tree --color=always --all --icons=always --no-git --git-ignore {} | head -200' "$@")
fi

if [[ -z $selected ]]; then
  exit 0
fi

selected_name=$(basename "$selected" | tr . _)
tmux_running=$(pgrep tmux)

if [[ -z $TMUX ]] && [[ -z $tmux_running ]]; then
  tmux new-session -s "$selected_name" -c "$selected"
  exit 0
fi

if ! tmux has-session -t="$selected_name" 2>/dev/null; then
  tmux new-session -ds "$selected_name" -c "$selected"
fi

tmux switch-client -t "$selected_name"
