#!/usr/bin/env bash

if [[ $# -eq 1 ]]; then
    selected=$1
else
    # ls all tmux sessions; take the first word; remove last character (which is ':'); pipe it through fzf
    selected=$(tmux ls | sed 's/ .*//' | sed 's/.$//' | fzf --style full -m) 
fi
 
for session in $selected; do
    tmux kill-ses -t "$session"
done

