import = [
    "~/.config/alacritty/themes/catppuccin-mocha.toml"
]

[colors]
draw_bold_text_with_bright_colors = true

[font]
size = 14

[font.bold]
family = "JetBrainsMono Nerd Font"

[font.italic]
family = "JetBrainsMono Nerd Font"

[font.normal]
family = "JetBrainsMono Nerd Font"
style = "Regular"

[window]
decorations = "Buttonless"

[window.padding]
x = 2
